name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: sdotnet
      run: dir  
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name : a
      uses: actions/upload-artifact@v1
      with: 
          name: dani2
          path: dani/Program.cs
      
